name: Publish package to Gitlab registry

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.22.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Configure npm for GitLab registry
        run: |
          echo "@virtuoso:registry=https://gitlab.virtuosohub.ai/api/v4/projects/11/packages/npm/" >> ~/.npmrc
          echo "//gitlab.virtuosohub.ai/api/v4/projects/11/packages/npm/:_authToken=${{ secrets.GITLAB_TOKEN }}" >> ~/.npmrc


      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build:clean

      - name: Publish (changesets)
        env:
          NPM_CONFIG_REGISTRY: https://gitlab.virtuosohub.ai/api/v4/projects/11/packages/npm/
          NODE_AUTH_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          set -e
          pnpm compat
          pnpm changeset publish || (
            code=$?
            if [ $code -ne 0 ]; then
              echo "changeset publish failed with code $code"
              exit $code
            fi
          )
